### PR TITLE
Japanese translation

### PR DESCRIPTION
**Pull request by akihito-takeuchi**
Japanese translation work in progress

### CODE REVIEW

**Comment by martinheidegger** [comment]
@masashi-t-h @akihito-takeuchi すごいです！今の状態はどうですか？

**Comment by masashi-t-h** [comment]
@martinheidegger 11/17のNodeSchool で日本語のレビューをする予定です。

**Comment by martinheidegger** [comment]
土曜日に NodeFest の NodeSchool がありますので、そのときまたはその前にレビューするのがどうですか？（私ではなくて）

**Comment by akihito-takeuchi** [comment]
I'll go through the translations and request you to merge the changes before NodeFest. We may have another merge request after the review on 17th though..

**Comment by akihito-takeuchi** [comment]
I'v reviewed and updated the translations. Could you merge our changes? I noticed followings during review.

* In English version of keywise exercise, there are some words 'command-line' in the explanation of argument. I don't think they are needed.

* Should I create ./i18n/help/ja.md file also?

Please let me know your comments!

**Comment by martinheidegger** [comment]
I merged the current solution. Thank you for your great work!

**Pull request merged**
