### PR TITLE
New workshopper (attempt #2)

### PR DESCRIPTION
**Pull request by martinheidegger**
Okay this is a crazy rewrite of most of levelmeup. 
It is ...
- [x] updated to all the latest dependencies
- [x] using workshopper-adventure
- [x] Not program based but module based
- [x] prepared for internationalization
- [x] testable using `npm test`
- [x] linted using [standard](http://standardjs.com)
- [x] significantly reduced in code-complexity
- [x] using markdown for rendering instead of txt

It would be lovely if someone could take the time to review it.

### CODE REVIEW

**Comment by jpwesselink** [comment]
I've started reviewing this, I'll let you know tomorrow!

**Comment by ralphtheninja** [comment]
A lot of commits. I think I'll just do the workshop and not focus as much on reviewing the code.

**Comment by ralphtheninja** [comment]
@martinheidegger I noticed two things while running the tests.

* It seems that the `./test/get_your_level_on/invalid_03.js` takes 10 seconds to finish
* First time I ran the tests they passed, but not the second and the third time they worked so something is a bit shaky, see output below


```
  59 passing (56s)
  2 failing

  1) Testing exercises ./test/basics_put/valid_01.js (3:1)       :
     Uncaught 
  rror
      at /home/lms/src/workshopper/levelmeup/node_modules/workshopper-adventure-test/spec/exercises.js:67:15
      at ChildProcess.exithandler (child_process.js:213:5)
      at emitTwo (events.js:106:13)
      at ChildProcess.emit (events.js:191:7)
      at maybeClose (internal/child_process.js:877:16)
      at Socket.<anonymous> (internal/child_process.js:334:11)
      at emitOne (events.js:96:13)
      at Socket.emit (events.js:188:7)
      at Pipe._handle.close [as _onclose] (net.js:498:12)

  2) Testing exercises ./test/horse_js_tweets/invalid_01.js (7:0)        :
     Uncaught Error:   You have 4 challenges left.  
   
  Type 'levelmeup' to show the menu.  
   

      at /home/lms/src/workshopper/levelmeup/node_modules/workshopper-adventure-test/spec/exercises.js:63:15
      at ChildProcess.exithandler (child_process.js:197:7)
      at emitTwo (events.js:106:13)
      at ChildProcess.emit (events.js:191:7)
      at maybeClose (internal/child_process.js:877:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by jpwesselink** [comment]
```
Object.keys(obj).forEach(function (key) {
  db.put(key, obj[key])
})
db.close(callback)
```

Probably has to do with https://github.com/Level/leveldown/issues/32#issuecomment-254081211

**Comment by ralphtheninja** [comment]
It seems I no longer get the previous output when something is successful:

```
$ levelmeup verify 01.js             
  You have 11 challenges left.       
                                     
  Type 'levelmeup' to show the menu. 
```

Maybe this is supposed to happen, I'm not sure.

**Comment by martinheidegger** [comment]
- `./test/get_your_level_on/invalid_03.js` takes 10 seconds to test if there is a timeout after 10 
- The instability should be related to the closing of the database.

**Comment by martinheidegger** [comment]
I just published https://www.npmjs.com/package/exec-module which should make the execution not just more stable but also allow us to give better error messages. This PR should probably be updated to reflect those changes.

**Comment by ralphtheninja** [comment]
> @ralphtheninja
> You mean that there should be more text, right?

@martinheidegger Yep!

**Comment by martinheidegger** [comment]
- [x] Using exec-module now
- [x] Updated to a fresh latest version of workshopper-adventure that should work smoothly.

_We have Nodeschool Tokyo in a little more than 24h and it would be awesome if it could be reviewed before that_

**Comment by martinheidegger** [comment]
@ixkaito reviewed it and I merged a PR, merging this workshopper with master since there has been no further review.

**Pull request merged**
