### PR TITLE
update level dependency + readme + license (gah can't spell)

### PR DESCRIPTION
**Pull request by ralphtheninja**

### CODE REVIEW

**Comment by juliangruber** [comment]
:rocket: !

**Comment by No9** [comment]
@ralphtheninja any reason this lost the +no-false-attribs License?

**Comment by ralphtheninja** [comment]
@No9 It says MIT in the readme

**Comment by No9** [comment]
https://github.com/ralphtheninja/levelmeup/commit/7867b757a6aa8dd26db5c784e365c47291069c6d#diff-9879d6db96fd29134fc802214163b95aL4 
Shows +no-false-attribs

**Comment by ralphtheninja** [comment]
Aye. Well I updated it to plain MIT since I have been doing that on many other projects. Should I revert it to +no-false-attribs?

**Comment by ralphtheninja** [comment]
cc @rvagg

**Comment by rvagg** [comment]
remove +no-false-attribs, I've been banishing it from all of my projects, all of the core levelmeup contributors are in this thread so if nobody disagrees then it's all good!

**Pull request merged**
