### PR TITLE
Fixed @raynos' twitter handle

### PR DESCRIPTION
**Pull request by ArtskydJ**

### CODE REVIEW

**Comment by juliangruber** [comment]
+1

**Comment by juliangruber** [comment]
@rvagg mind giving me write access to this repo?

**Comment by rvagg** [comment]
done, accept invite for it and you'll be in

**Comment by rvagg** [comment]
```$ npm owner add juliangruber levelmeup
npm http request GET https://registry.npmjs.org/-/user/org.couchdb.user:juliangruber
npm http 200 https://registry.npmjs.org/-/user/org.couchdb.user:juliangruber
npm http request GET https://registry.npmjs.org/levelmeup
npm http 200 https://registry.npmjs.org/levelmeup
npm http request PUT https://registry.npmjs.org/levelmeup/-rev/56-ecd71f1b84babe23ed6406229066bef6
npm http 200 https://registry.npmjs.org/levelmeup/-rev/56-ecd71f1b84babe23ed6406229066bef6
+ juliangruber (levelmeup)
$ npm owner add ralphtheninja levelmeup
npm http request GET https://registry.npmjs.org/-/user/org.couchdb.user:ralphtheninja
npm http 200 https://registry.npmjs.org/-/user/org.couchdb.user:ralphtheninja
npm http request GET https://registry.npmjs.org/levelmeup
npm http 200 https://registry.npmjs.org/levelmeup
npm http request PUT https://registry.npmjs.org/levelmeup/-rev/57-5b4583fec1850b8eb721193148390d3d
npm http 200 https://registry.npmjs.org/levelmeup/-rev/57-5b4583fec1850b8eb721193148390d3d
+ ralphtheninja (levelmeup)
```

/cc @ralphtheninja

**Comment by juliangruber** [comment]
thank you @rvagg!

**Pull request merged**
